language: objective-c
osx_image: xcode8
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Mundus_ios.xcworkspace
  - SCHEME="Mundus_ios"
  - SDK=iphonesimulator10.0
  - DESTINATION="OS=10.0,name=iPhone 7"
  
notifications:
  email: false

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES -enableCodeCoverage YES test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 0ec85e0c-c7be-4fe0-8e18-085d30467da8
